### PR TITLE
Added object support

### PR DESCRIPTION
**Pull request by dawnerd**
@jgallen23 For some reason this test `should trigger on click as object` isn't working and can't figure out why. Maybe you can see if I made a dumb mistake?

### CODE REVIEW

**Comment by jgallen23** [comment]
Can we approach a different way?  Check if the first param is an object, if so, loop through that and call the parent function with the params and return.  Not sure that'll fix the issue, but it'll clean up the code quite a bit

**Comment by dawnerd** [comment]
Oh I like that idea much more.

**Comment by dawnerd** [comment]
Test still fails doing it that way, so maybe my test is bad?

**Comment by jgallen23** [comment]
fixed

**Comment by dawnerd** [comment]
Nice!

**Pull request merged**
